version: "3.8"
services:
  node:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 80:3000
    env_file:
      - .production.env
    networks:
      - webconvention
  sfu:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    restart: unless-stopped
    ports:
      - "5000-5200:5000-5200/udp"
      - "7005:7000"
  postfix:
    image: boky/postfix
    restart: unless-stopped
    ports:
      - "1587:587"
    environment:
      - ALLOWED_SENDER_DOMAINS=on-webconvention.de
    networks:
      - webconvention
networks:
  webconvention: {}